---
- name: install python
  hosts:  ansible_clients
  remote_user:  root
  become: true
  
  tasks:
    - name: install pre-requisites
      apt:
        name: software-properties-common
        state:  present
        update_cache: yes

    - name: install python
      apt:
        name: python3
        state:  present
    - name: check python
      shell:  'python3 --version'
      register: comband_output
    - debug:
              var:  comband_output.stdout_lines

    - name: install pip
      apt:
        name: pip
        state:  present

    - name: install git
      apt:
        name: git
        state:  present

#    - name: install flask
 #     pip:
  #      name: flask
   #     state:  present

    #- name: check flask
     # shell:  'flask --version'
      #register: comband_output
   # - debug:
    #    var:  comband_output.stdout_lines
#
    - name: cloning helloworld repo
      git:
        repo: https://github.com/Sysnove/flask-hello-world.git
        dest: /home/ubuntu/repos/
        clone:  yes
        update: yes

    - name: creating or updating requirements file
      copy:
        dest: /home/ubuntu/repos/requirements.txt
        content:  flask
		
    - name: install venv
      pip:
        name: virtualenv
        state:  present

    - name: create venv
      pip:
        requirements: /home/ubuntu/repos/requirements.txt
        virtualenv: /home/ubuntu/envs/hello
        virtualenv_python:  python3

 - name: activate
      shell:  'bash file.sh'
