---
- name: install python
  hosts:  ansible_clients
  remote_user:  root
  become: true
  environment:
    FLASK_APP: hello.py
    
  tasks:
    - name: install pre-requisites
      apt:
        name: software-properties-common
        state:  present
        update_cache: yes

    - name: install python
      apt:
        name: python3
        state:  present
    - name: check python
      shell:  'python3 --version'
      register: comband_output
    - debug:
              var:  comband_output.stdout_lines

    - name: install pip
      apt:
        name: pip
        state:  present
    
    - name: install git
      apt:
        name: git
        state:  present

    - name: install flask
      pip:
        name: flask
        state:  present

    - name: check flask
      shell:  'flask --version'
      register: comband_output
    - debug:
        var:  comband_output.stdout_lines

    - name: cloning helloworld repo
        git:
          repo: https://github.com/Sysnove/flask-hello-world.git
          dest: /home/ubuntu/repos/
          clone:  yes
          update: yes

    - name: exporting flask variable
      # shell:  'cd /home/ubuntu/repos'
      # environment:
      # FLASK_APP:  hello.py
      shell:  'flask run'
      register: comband_output
    - debug:
        var:  comband_output.stdout_lines
